### ISSUE TITLE
User Story: Publish A Poll

### ISSUE THREAD

**Issue by roc-11** [roc-11/love-running#5]
As an **administrator** I can **pick the expiry date while publishing the poll** in order to **automatically hide the poll**.

##

## Tasks 
- [ x ] Update the admin module view: the poll design (HML and CSS) to include the date picker.
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon".
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days. 
- [ ] Update the controller function.
- [ ] Update unit test scripts.
- [ ] Test the functionality.
